/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CmpButton {
    'disabled': boolean;
    'primary': boolean;
    'secondary': boolean;
    'size': 'extra-large' | 'large' | 'medium' | 'small' | 'extra-small';
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLCmpButtonElement extends Components.CmpButton, HTMLStencilElement {}
  var HTMLCmpButtonElement: {
    prototype: HTMLCmpButtonElement;
    new (): HTMLCmpButtonElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'cmp-button': HTMLCmpButtonElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface CmpButton {
    'disabled'?: boolean;
    'primary'?: boolean;
    'secondary'?: boolean;
    'size'?: 'extra-large' | 'large' | 'medium' | 'small' | 'extra-small';
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'cmp-button': CmpButton;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'cmp-button': LocalJSX.CmpButton & JSXBase.HTMLAttributes<HTMLCmpButtonElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


